### ISSUE TITLE
Make ExpressionType.LITERAL as default for expression in decision's fluent API.

### ISSUE THREAD

**Issue by mariuszkumor** [powerflows/powerflows-dmn#62]

**Comment by stlhrt** [comment]
I partially did this in writer branch

**Comment by mariuszkumor** [comment]
@stlhrt I'm adding a reference to the pull request where partially has been done https://github.com/powerflows/powerflows-dmn/pull/64/files

**Comment by mariuszkumor** [comment]
Additional set default expression if not set by a user.
